# Generated by Django 5.0.6 on 2024-05-31 10:56

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_checkout_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('stripe_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Stripe ID')),
                ('phone_number', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Phone number')),
                ('date_of_birth', encrypted_model_fields.fields.EncryptedDateField(verbose_name='Date of birth')),
                ('postal_code', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Postal code')),
                ('address', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Address')),
            ],
        ),
    ]
