# Generated by Django 5.0.6 on 2024-06-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
